title: "Shiroff"
description: "Static site converted for GitHub Pages"
author: "Site Owner"
url: "https://shiroff.com"
theme: minima

markdown: kramdown
kramdown:
  input: GFM

# Optional: simple nav labels
nav:
  - title: "Welcome"
    url: /home
  - title: "About"
    url: /about/

# Enable these only if adding plugins supported by Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
